[release/8.0.1xx-sr8] Update the mac/iOS workloads (#24321)
* Update the mac/iOS workloads

### Description of Change

We are "multitargeting" to 17.0, but this was only really supported in the latest iOS workloads.

Right now, the 17.0 TFM version will always be 17.2.

Maui 8.0.80 with TFM 17.0 is actually 
```
// Microsoft.iOS, Version=17.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
```

When I use the latest SDKs and workloads and try multitarget SkiaSharp to 17.0 because I want to support everyone, I get this error:

> CSC : error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.MacCatalyst, Version=17.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Microsoft.MacCatalyst' with identity 'Microsoft.MacCatalyst, Version=17.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [D:\GitHub\SkiaSharp\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Core\SkiaSharp.Views.Maui.Core.csproj::TargetFramework=net8.0-maccatalyst17.0]

I can't use 17.2 in SkiaSharp with the new SDK as the only TFM versions that are supported are 17.0 and 17.5

* no longer an issue