Install Microsoft.NET.Workload.Emscripten.Manifest
This solves the build error:

    Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.2' is lower than version '6.0.1' required by manifest 'microsoft.net.workload.mono.toolchain' [/Users/builder/azdo/_work/2/s/bin/dotnet/sdk-manifests/6.0.200/microsoft.net.workload.mono.toolchain/WorkloadManifest.json]
        at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
        at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
        at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds)
        at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_0(ParseResult appliedOption)
        at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
        at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
        at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
        at Microsoft.DotNet.Cli.Program.Main(String[] args)