[android] ignore warnings for PreserveAttribute
We were hitting this in one file:

  src\Core\src\Platform\Android\NavigationLayout.cs(11,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(16,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(21,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(26,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'

For now, let's disable this warning. We probably don't want to add
this to `$(NoWarn)`, because turning off CS0618 would disable too
much. You'd still want warnings for other obsolete APIs.