[workload] add missing Microsoft.Extensions.Primitives
Manually testing the workload again, I found one more dependency that
was missing:

    System.TypeLoadException: Could not load type of field 'Microsoft.Extensions.Configuration.ConfigurationRoot:_changeToken' (2) due to: Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.

I missed this one in a12e5147, because NuGet brought in transitive
dependencies when I was testing. I added each `@(PackageReference)` to
the project template until it ran successfully. This package came in
automatically, and I didn't notice...