Bump to new AndroidX packages (#825)
We have new AndroidX packages produced from:

https://github.com/xamarin/AndroidX/pull/247

After updating I ran into:

    C:\src\maui\src\Compatibility\Core\src\Android\CollectionView\SelectableViewHolder.cs(44,25):
        error CS0618: 'RecyclerView.ViewHolder.AdapterPosition' is obsolete: 'deprecated' [C:\src\maui\src\Compatibility\Core\src\Compatibility-net6.csproj]
    C:\src\maui\src\Compatibility\Core\src\Android\CollectionView\SelectableItemsViewAdapter.cs(70,9):
        error CS0618: 'RecyclerView.ViewHolder.AdapterPosition' is obsolete: 'deprecated' [C:\src\maui\src\Compatibility\Core\src\Compatibility-net6.csproj]
        0 Warning(s)
        2 Error(s)

`AdapterPosition` is indeed obsolete:

https://stackoverflow.com/a/63148812

It appears we can use `BindingAdapterPosition`, because the deprecated
code is basically:

    @Deprecated
    public final int getAdapterPosition() {
        return getBindingAdapterPosition();
    }