[net7.0] Update dependencies from xamarin/xamarin-android (#9636)
* Update dependencies from https://github.com/xamarin/xamarin-android build 7.0.1xx-rc1-92c290be2e02bb27e08c064190750f34c6a0cc6e-1

Microsoft.Android.Sdk.Windows
 From Version 33.0.0-rc.1.125 -> To Version 33.0.0-rc.1.141

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-rc.1.22374.1 -> To Version 7.0.100-rc.2.22417.1 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-android build 7.0.1xx-rc1-29a0fe0ebc671706e54c1637fe300310b95f15aa-1

Microsoft.Android.Sdk.Windows
 From Version 33.0.0-rc.1.125 -> To Version 33.0.0-rc.1.142

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-rc.1.22374.1 -> To Version 7.0.100-rc.1.22423.7 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-android build 7.0.1xx-rc1-fe619530aa3d959525ad8d4384c783c6d4846410-1

Microsoft.Android.Sdk.Windows
 From Version 33.0.0-rc.1.125 -> To Version 33.0.0-rc.1.143

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-rc.1.22374.1 -> To Version 7.0.100-rc.1.22423.7 (parent: Microsoft.Android.Sdk.Windows

* [net7.0] Update dependencies from xamarin/xamarin-macios (#9663)

Microsoft.iOS.Sdk , Microsoft.MacCatalyst.Sdk , Microsoft.macOS.Sdk , Microsoft.tvOS.Sdk
 From Version 15.4.1006-rc.1 -> To Version 15.4.1009-rc.1

* Ignore a new case of CS0809

Fixes:

    src/Core/src/Platform/Android/MauiAppCompatActivity.Lifecycle.cs(25,24):
    error CS0809: Obsolete member 'MauiAppCompatActivity.OnBackPressed()' overrides non-obsolete member 'Activity.OnBackPressed()'

It is apparently now a warning to override a non-obsolete method and
add `[Obsolete]`.

* Fix more CS0809 warnings

    Core/src/Android/Renderers/FormsWebViewClient.cs(30,24): error CS0809: Obsolete member 'FormsWebViewClient.ShouldOverrideUrlLoading(WebView, string)' overrides non-obsolete member 'WebViewClient.ShouldOverrideUrlLoading(WebView?, string?)'
    Core/src/Android/Renderers/FormsWebViewClient.cs(90,24): error CS0809: Obsolete member 'FormsWebViewClient.OnReceivedError(WebView, ClientError, string, string)' overrides non-obsolete member 'WebViewClient.OnReceivedError(WebView?, ClientError, string?, string?)'
    Core/src/Android/AppCompat/FormsAppCompatActivity.cs(73,24): error CS0809: Obsolete member 'FormsAppCompatActivity.OnBackPressed()' overrides non-obsolete member 'Activity.OnBackPressed()'

* Update dependencies from https://github.com/xamarin/xamarin-android build 7.0.1xx-rc1-2bf5153313128b4705c117dbdf9b83c04650c841-1

Microsoft.Android.Sdk.Windows
 From Version 33.0.0-rc.1.125 -> To Version 33.0.0-rc.1.144

Dependency coherency updates

Microsoft.NET.Workload.Emscripten.Manifest-7.0.100,Microsoft.NETCore.App.Ref,Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.0-rc.1.22362.2 -> To Version 7.0.0-rc.1.22411.1 (parent: Microsoft.NETCore.App.Ref

* Fixes for new runtime and emsdk workload names

* Only enable UseInterpreter for Android?

Context: https://github.com/dotnet/runtime/issues/74628

Let's see if this gets past the errors on CI

* Bump to a newer .NET 6/MAUI build

Fixes this error on net6.0 test lanes:

    Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm\staticwebassets.build.json' not found.
    Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x86\staticwebassets.build.json' not found.
    Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json' not found.
    Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(658,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x64\staticwebassets.build.json' not found.

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: dotnet-maestro[bot] <42748379+dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>