[main] Update dependencies from xamarin/xamarin-android (#1842)
* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview7-d306ec847373bedc8995de8a17fd4e482697e824-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.7.100 -> To Version 30.0.100-preview.7.104

Dependency coherency updates

Microsoft.Extensions.Hosting.Abstractions,Microsoft.Extensions.DependencyInjection.Abstractions,Microsoft.Extensions.DependencyInjection,Microsoft.Extensions.Configuration.Abstractions,Microsoft.Extensions.Configuration,Microsoft.Extensions.Logging.Abstractions,Microsoft.Extensions.Logging,Microsoft.Extensions.Logging.Console,Microsoft.Extensions.Logging.Debug,Microsoft.Extensions.FileProviders.Abstractions,System.CodeDom
 From Version 6.0.0-preview.7.21373.17 -> To Version 6.0.0-preview.7.21376.17 (parent: Microsoft.AspNetCore.App.Runtime.win-x64

* [android] ignore warnings for PreserveAttribute

We were hitting this in one file:

  src\Core\src\Platform\Android\NavigationLayout.cs(11,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(16,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(21,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'
  src\Core\src\Platform\Android\NavigationLayout.cs(26,4): error CS0618: 'PreserveAttribute' is obsolete: 'Please use [System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute]'

For now, let's disable this warning. We probably don't want to add
this to `$(NoWarn)`, because turning off CS0618 would disable too
much. You'd still want warnings for other obsolete APIs.

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>