Add `CA1420` to `$(NoWarn)` for Windows
Fixes the error:

    src\DeviceDisplay\DeviceDisplay.uwp.cs(240,92): error CA1420: Delegates with managed types as parameters or the return type require runtime marshalling to be enabled in the assembly where the delegate is defined.