[blazorwebview] fix <ProjectReference/> in .NET 6 sample
When I build `Maui.Controls.Sample-net6.csproj` by itself I get lots of errors like:

    Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Index.razor.cs(65,59): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
    12 Warning(s)
    81 Error(s)

I don't think we need the `$(BuildForNet6)` condition here, because this is a .NET 6 project.