[xamlc] fix `assembly=mscorlib` namespaces in `Release` mode (#14301)
* [xamlc] fix `assembly=mscorlib` namespaces in `Release` mode

Fixes: https://github.com/dotnet/maui/issues/9471
Context: https://learn.microsoft.com/dotnet/standard/assembly/type-forwarding

Using something like this fails in `Release` builds on some platforms:

    <ContentPage
        ...
        xmlns:sys="clr-namespace:System;assembly=mscorlib">
        <RadioButton>
            <RadioButton.Value>
                <sys:Int32>1</sys:Int32>
            </RadioButton.Value>
        </RadioButton>
    </ContentPage>

With the exception:

    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
    ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 11:22. Type sys:Int32 not found in xmlns clr-namespace:System;assembly=mscorlib
    at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)

What's going on here is that `mscorlib.dll` in .NET 5+ is an assembly
that only contains type forwards. For example:

    [assembly: TypeForwardedTo(typeof(Int32))]

Where `System.Int32` is actually in `System.Private.CoreLib.dll`.

In builds that use `PublishTrimmed=true` it can get trimmed away and
the type forwards disappear. Call sites will be updated with the
"real" assembly. You'd see different behavior in `Debug` vs `Release`
(iOS has to run the trimmer even in `Debug` mode, while Android &
Windows do not).

I added a unit test for this scenario, which of course passes due to
unit tests projects not using trimming. I had to add an on-device
test, which only failed in `Release` mode where I tested it on
Android.

To solve the issue, I added a fallback for `System.Private.CoreLib`:

    // As a fallback, for assembly=mscorlib try assembly=System.Private.CoreLib
    if (xmlnsDefinitionAttribute.AssemblyName == "mscorlib")
    {
        potentialTypes.Add(new(typeName, xmlnsDefinitionAttribute.ClrNamespace, "System.Private.CoreLib"));
    }

This seems like a safe fix, because it still attempts `mscorlib` first.

The XAML editor's Intellisense suggests `clr-namespace:System;assembly=mscorlib`
quite easily. I think we have to support it.