[net8.0] use latest .NET 8 SDK and mobile workloads (#12520)
Changes: https://github.com/xamarin/xamarin-android/compare/8a20803...c1efcb5
Changes: https://github.com/xamarin/xamarin-macios/compare/df0151d...6b1b9f3
Changes: https://github.com/dotnet/installer/compare/8c1708f...9962c6a
Changes: https://github.com/dotnet/runtime/compare/5108757...5da4a9e
Changes: https://github.com/dotnet/emsdk/compare/aecb1c7...66b9845

Updates:

* Microsoft.Android.Sdk.Windows: from 34.0.0-preview.1.50 to 34.0.0-preview.1.127
* Microsoft.iOS.Sdk: from 16.1.585-net8-p1 to 16.2.126-net8-p1
* Microsoft.Dotnet.Sdk.Internal: from 8.0.100-alpha.1.22526.2 to 8.0.100-alpha.1.23063.11
* Microsoft.NETCore.App.Ref: from 8.0.0-alpha.1.22524.5 to 8.0.0-alpha.1.23058.2
* Microsoft.NET.Workload.Emscripten.net7.Manifest-8.0.100: from 8.0.0-alpha.1.22510.1 to 8.0.0-alpha.1.22620.1

~~ Workloads ~~

The .NET SDK has a workaround for `microsoft.net.workload.mono.toolchain`:

https://github.com/dotnet/sdk/commit/f5cb7e3c3eb631d13a1bdc6033f399cf8a1ceadb

* HACK: copy folder to `microsoft.net.workload.mono.toolchain.net8` for now until this is resolved.

~~ Android ~~

The biggest changes now in xamarin-android/main are:

* Android enums now have appropriate `[SupportedOSPlatform]` attributes.
  This caused various new warnings in MAUI.

Example:

    src/Essentials/test/DeviceTests/Tests/Vibration_Tests.cs(16,62): error CA1416: This call site is reachable on: 'Android' 21.0 and later. 'BuildVersionCodes.M' is only supported on: 'android' 23.0 and later.
    src/Essentials/test/DeviceTests/Tests/Vibration_Tests.cs(34,62): error CA1416: This call site is reachable on: 'Android' 21.0 and later. 'BuildVersionCodes.M' is only supported on: 'android' 23.0 and later.

* Android now has a new implementation of `Resource.designer.cs`:

https://github.com/xamarin/xamarin-android/commit/dc3ccf28cdbe9f8c0a705400b83c11a85c81a980

We had to make various API changes for a new `Resource` type. Some we we be able to get rid of in the future, after we get:

https://github.com/xamarin/xamarin-android/pull/7721

* Remove IsMarshmallowOrNewer, IsNougatOrNewer

It appears the analyzer can't tell these values are using `OperatingSystem.IsAndroidVersionAtLeast()`.

It seems we can just use this API directly instead.

* Allow `$(AndroidEnableMarshalMethods)` again

This has the fix:

https://github.com/xamarin/xamarin-android/commit/22f10b2edec9e40a139c04564f96d8c1b3c17526

Fixes: https://github.com/dotnet/maui/issues/11605

~~ Other changes ~~

* [essentials, compatibility] disable trimming for netstandard

* Minor iOS API Changes

* Fix CA2200 in test

Fixes:

    src\Controls\tests\Core.UnitTests\ImageButtonUnitTest.cs(215,6): error CA2200: Re-throwing caught exception changes stack information

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>