Avoid KVO on CALayer by introducing an Apple PlatformInterop (#30861)
### Description of Change

On a recent `macios` workload, a regression caused issues with
`WeakReference`s bringing lots of crashes in our app, all tied to
`KVO`s.

It potentially causes an issue with hot-reload which may or may not be
related.
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Maui.Platform.StaticCAShapeLayer'.
   at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o) in /Users/builder/azdo/_work/2/s/macios/src/ObjCRuntime/ThrowHelper.cs:line 52
   at Foundation.NSObject.get_SuperHandle() in /Users/builder/azdo/_work/2/s/macios/src/Foundation/NSObject2.cs:line 660
   at CoreAnimation.CALayer.RemoveFromSuperLayer() in /Users/builder/azdo/_work/2/s/macios/src/build/dotnet/ios/generated-sources/CoreAnimation/CALayer.g.cs:line 783
   at Microsoft.Maui.Platform.StaticCAShapeLayer.RemoveFromSuperLayer()
   at Microsoft.Maui.Platform.ContentView.RemoveContentMask()
   at Microsoft.Maui.Platform.ContentView.WillRemoveSubview(UIView uiview)
   at Foundation.NSObject.ReleaseManagedRef() in /Users/builder/azdo/_work/2/s/macios/src/Foundation/NSObject2.cs:line 458
   at Foundation.NSObject.NSObject_Disposer.Drain(NSObject ctx) in /Users/builder/azdo/_work/2/s/macios/src/Foundation/NSObject2.cs:line 1072
```

Given we're never unsubscribing from the KVO legacy observer, what we're
doing may lead to issues.

This PR introduces an `.xcframework` for Apple platforms which could
really help in the future also for other purposes.

I moved the observer to a `Swift` implementation which relies on the new
KVO API which lets you skip the unsubscribe and all those managed
weak-refs.

### Security

For security concerns, the MAUI team should use the attached script to
re-build the `.xcframework.zip` and commit that on my behalf like we did
with Android in the past.

<img width="759" height="62" alt="image"
src="https://github.com/user-attachments/assets/bd372451-9e39-4a24-9d59-b0dbdadd5258"
/>

This is how the project looks like:
<img width="410" height="406" alt="image"
src="https://github.com/user-attachments/assets/7be12553-40ec-4afc-a88e-3109c5c0eb2e"
/>

---------

Co-authored-by: Rolf Bjarne Kvinge <rolf@xamarin.com>