[android] remove Xamarin.AndroidX.Legacy.Support.V4
In reviewing:

https://github.com/dotnet/maui/issues/10901#issuecomment-1354975448

I found `Xamarin.AndroidX.Legacy.Support.V4` triggers the warning:

    R8 : warning : Missing class androidx.window.extensions.WindowExtensions

`AndroidX.Legacy.Support.V4` is a package for supporting *really* old
Android API levels like 7, 11, etc.

Details here: https://stackoverflow.com/a/59484158

The Android workload in .NET 6/7 only supports API 21+. That made me
think, why is .NET MAUI using `AndroidX.Legacy.Support.V4` at all?
Turns out, it's not!

I tried directly removing the package, and got:

    src\Core\src\Platform\Android\MauiSwipeRefreshLayout.cs(10,16): error CS0234: The type or namespace name 'SwipeRefreshLayout' does not exist in
the namespace 'AndroidX' (are you missing an assembly reference?)

It looks like this is just a dependency of
`Xamarin.AndroidX.Legacy.Support.V4`. Instead we can just use this
package directly instead:

    <PackageReference Include="Xamarin.AndroidX.SwipeRefreshLayout" Version="1.1.0.10" />

The end result, is we just removed Android packages that are not used
at all. We still use the same library for `SwipeRefreshLayout`.

~~ Results ~~

Android app sizes improved from this change:

    > apkdiff -f com.companyname.maui_before-Signed.apk com.companyname.maui_after-Signed.apk
    Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
    +   1,598,040 classes.dex
    -           6 META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version *1
    -           6 META-INF/androidx.legacy_legacy-support-core-ui.version *1
    -           6 META-INF/androidx.legacy_legacy-support-v4.version *1
    -           6 META-INF/androidx.media_media.version *1
    -         455 assemblies/assemblies.blob
    -         564 res/layout/notification_media_action.xml *1
    -         744 res/layout/notification_media_cancel_action.xml *1
    -       1,292 res/layout/notification_template_media.xml *1
    -       1,584 META-INF/BNDLTOOL.SF
    -       1,584 META-INF/MANIFEST.MF
    -       1,696 res/layout/notification_template_big_media.xml *1
    -       1,824 res/layout/notification_template_big_media_narrow.xml *1
    -       2,456 resources.arsc
    -       2,756 res/layout/notification_template_media_custom.xml *1
    -       2,872 res/layout/notification_template_lines_media.xml *1
    -       3,044 res/layout/notification_template_big_media_custom.xml *1
    -       3,216 res/layout/notification_template_big_media_narrow_custom.xml *1
    -   2,030,636 classes2.dex
    Summary:
    -      24,111 Other entries -0.35% (of 6,880,759)
    -     432,596 Dalvik executables -3.46% (of 12,515,440)
    +           0 Shared libraries 0.00% (of 12,235,904)
    -     169,179 Package size difference -1.12% (of 15,123,185)

Most notably, `*.dex` executables are ~432kb smaller. So small, in
fact, that the project template no longer needs multi-dex anymore!