[main] Update dependencies from xamarin/xamarin-android (#4787)
* Update dependencies from https://github.com/xamarin/xamarin-android build main-ebdd4b826cc208202ac1793484cad2fe0036abc2-1

Microsoft.Android.Sdk.Windows
 From Version 31.0.200-preview.14.84 -> To Version 31.0.200-preview.14.91

Dependency coherency updates

Microsoft.NET.Workload.Emscripten.Manifest-6.0.100,Microsoft.NETCore.App.Ref
 From Version 6.0.0 -> To Version 6.0.2 (parent: Microsoft.NETCore.App.Ref

* Install Microsoft.NET.Workload.Emscripten.Manifest

This solves the build error:

    Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.2' is lower than version '6.0.1' required by manifest 'microsoft.net.workload.mono.toolchain' [/Users/builder/azdo/_work/2/s/bin/dotnet/sdk-manifests/6.0.200/microsoft.net.workload.mono.toolchain/WorkloadManifest.json]
        at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
        at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
        at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds)
        at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_0(ParseResult appliedOption)
        at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
        at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
        at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
        at Microsoft.DotNet.Cli.Program.Main(String[] args)

* Update dependencies from https://github.com/xamarin/xamarin-android build main-d73e048af287b32c69d825191337927081bf8d3c-1

Microsoft.Android.Sdk.Windows
 From Version 31.0.200-preview.14.84 -> To Version 31.0.200-preview.14.93

Dependency coherency updates

Microsoft.NET.Workload.Emscripten.Manifest-6.0.100,Microsoft.NETCore.App.Ref
 From Version 6.0.0 -> To Version 6.0.2 (parent: Microsoft.NETCore.App.Ref

* Use 6.0.0 and 6.0.1 versions of certain packages

* Update dependencies from https://github.com/xamarin/xamarin-android build main-0583ca1d3a44f4ffc6a29b487ef2b4ed33d2c067-1

Microsoft.Android.Sdk.Windows
 From Version 31.0.200-preview.14.84 -> To Version 31.0.200-preview.14.95

Dependency coherency updates

Microsoft.NET.Workload.Emscripten.Manifest-6.0.100,Microsoft.NETCore.App.Ref
 From Version 6.0.0 -> To Version 6.0.2 (parent: Microsoft.NETCore.App.Ref

* Bump ios to match #4798

* macios is on 6.0.300 already

* Update dependencies from https://github.com/xamarin/xamarin-android build main-0583ca1d3a44f4ffc6a29b487ef2b4ed33d2c067-1

Microsoft.Android.Sdk.Windows
 From Version 31.0.200-preview.14.84 -> To Version 31.0.200-preview.14.95

Dependency coherency updates

Microsoft.NET.Workload.Emscripten.Manifest-6.0.100,Microsoft.NETCore.App.Ref
 From Version 6.0.0 -> To Version 6.0.2 (parent: Microsoft.NETCore.App.Ref

* Update Versions.props

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>
Co-authored-by: redth <jondick@gmail.com>
Co-authored-by: Matthew Leibowitz <mattleibow@live.com>