Try to fix IL2091 in Tizen
src/Compatibility/Core/src/Tizen/Extensions/PageExtensions.cs(45,52): error IL2091: 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.PublicProperties' in 'Microsoft.Maui.Controls.MultiPage<T>'. The generic parameter 'T' of 'Microsoft.Maui.Controls.Compatibility.Platform.Tizen.PageExtensions.UpdateFocusTreePolicy<T>(MultiPage<T>)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.