[essentials] use AssemblyMetadata w/ IsTrimmable instead of Linkersafe
Context: https://github.com/xamarin/xamarin-android/pull/6054

This solves the warning (that is turned into an error):

    src/Essentials/src/AssemblyInfo/AssemblyInfo.android.cs(3,12): error CS0618: 'LinkerSafeAttribute' is obsolete: 'For .NET 6+, please use: [assembly: global::System.Reflection.AssemblyMetadata("IsTrimmable", "True")]'